<?php
declare(strict_types=1);
function getx(string $url,array $headers=[]): string {$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_ENCODING=>'',CURLOPT_TIMEOUT=>30,CURLOPT_USERAGENT=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/153 Safari/537.36',CURLOPT_HTTPHEADER=>array_merge(['Accept: text/html,application/xhtml+xml,application/json,*/*;q=0.8','Accept-Language: ar,fr;q=.9,en;q=.7'],$headers)]);$b=curl_exec($ch);$c=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if(!is_string($b)||$c<200||$c>=300)throw new RuntimeException("HTTP $c");return $b;}
foreach(['adsports'=>'https://www.sport24.rest/channels/adsports/1','dubai'=>'https://www.sport24.rest/channels/dubaisports/1','bein'=>'https://www.sport24.rest/channels/bein/1'] as $k=>$u){$h=getx($u);preg_match_all('/data-time=["\']([^"\']+)["\']/i',$h,$m);echo json_encode(['sport24'=>$k,'count'=>count($m[1]),'samples'=>array_slice($m[1],0,8)],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";}

$key=hex2bin('65a04b9b5591f27c837fac433274b494403e0eec5b43698060c28e1162d4460f');$iv=hex2bin('b7cc0a48d6d023bc1a2a670953ec5622');
$dec=function($body)use($key,$iv){$j=json_decode($body,true);if(isset($j['encrypted'])){$raw=openssl_decrypt(base64_decode($j['encrypted'],true),'aes-256-cbc',$key,OPENSSL_RAW_DATA,$iv);return json_decode($raw,true);}return $j;};
$enc=function($data)use($key,$iv){return base64_encode(openssl_encrypt(json_encode($data,JSON_UNESCAPED_SLASHES),'aes-256-cbc',$key,OPENSSL_RAW_DATA,$iv));};
$chs=$dec(getx('https://www.osn.com/apidata/channels?platform=Android'));$guid=$chs[0]['guid'];
foreach(['UTC','Africa/Casablanca'] as $tz){$z=new DateTimeZone($tz);$s=(new DateTimeImmutable('today',$z))->setTime(0,0);$e=$s->modify('+1 day');foreach([1,5] as $n){$g=array_map(fn($x)=>$x['guid'],array_slice($chs,0,$n));$data=['channelGuid'=>implode('|',$g),'startTime'=>$s->getTimestamp()*1000,'endTime'=>$e->getTimestamp()*1000];$url='https://www.osn.com/apidata/tv-schedule-timeline?t=batch1-time'.$data['startTime'].'-'.$data['endTime'].'-boxAndroid';try{$body=getx($url,['X-Encrypted-Data: '.$enc($data)]);$p=$dec($body);$list=0;foreach(($p['entries']??[]) as $x)$list+=count($x['listings']??[]);echo json_encode(['osn'=>true,'tz'=>$tz,'channels'=>$n,'entries'=>count($p['entries']??[]),'listings'=>$list],JSON_UNESCAPED_SLASHES)."\n";}catch(Throwable $ex){echo json_encode(['osn'=>false,'tz'=>$tz,'channels'=>$n,'error'=>$ex->getMessage()])."\n";}}}
